"""

BRILLIANT CHALLENGE

IS STRING A PALINDROME?

"""

import re


string = "EATAUDRYBERNITAEATVIVANBROOKSEATJENIEATMICHALELASANDRALATIAEATLIDIAEATDEANDRAEATSYBILEATMONROEEATLATRISHAALTAEATDERICKROSANNLEVILIBBYKIRSTENCHARLESEATELLYNEATJANEEEATSTASIAEATJULIETTARANDIEATNORBERTSAGEEATARACELIKATINAMERNAEATISAIASWINNIEEATARLETHAEATMILOCAMIEEATANNABELEATLEANORABERTHASYBLECHANAEATREAGANERICKVALENTINAEATDORETHEASEBASTIANKRISROBERTAEATIVONNEEAT"

string2 = "EAT"

if str(string) == str(string)[::-1]:
    print("Yes is palindrome")
else:
    print("Not a palindrome")

print(re.findall("EAT", string))

number = len(re.findall("EAT", string))
print(number)
